# 14 – Scikit-learn Preprocessing Pipeline

## Objective

This notebook explains how to build a complete preprocessing pipeline using Scikit-learn.

The main workflow is:

**Numerical Features → Imputation → Scaling**

**Categorical Features → Imputation → Encoding**

The notebook also explains `Pipeline`, `ColumnTransformer`, `fit()`, `transform()`, and `fit_transform()`.

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

df = pd.read_csv("Titanic-Dataset.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 1. What is a Preprocessing Pipeline?

A preprocessing pipeline is a sequence of data preprocessing steps performed in a fixed order.

For example:

Numerical Features:
**Missing Value Imputation → Scaling**

Categorical Features:
**Missing Value Imputation → One-Hot Encoding**

### Why use Pipelines?

Pipelines help to:

- Organize preprocessing steps.
- Apply transformations consistently.
- Reduce manual coding.
- Prevent data leakage.
- Ensure the same preprocessing is applied to training and test data.
- Make Machine Learning workflows easier to reproduce.

### Required Documentation

**Problem:**  
Different preprocessing steps need to be applied to different types of features.

**Analysis:**  
Numerical and categorical features require different preprocessing techniques.

**Technique Selected:**  
Scikit-learn `Pipeline` and `ColumnTransformer`.

**Reason:**  
They allow multiple preprocessing steps to be combined into one structured workflow.

**Implementation:**  
Separate numerical and categorical pipelines are created and combined.

**Result:**  
The preprocessing workflow becomes organized and reusable.

**Impact:**  
A consistent preprocessing process can improve model reliability and reduce data leakage.

In [2]:
print("Numerical and categorical preprocessing will be handled using separate pipelines.")

Numerical and categorical preprocessing will be handled using separate pipelines.

## 2. Why Use Pipelines?

A pipeline combines multiple preprocessing operations into a single workflow.

Instead of manually performing:

1. Missing value handling
2. Scaling
3. Encoding

we can place these operations inside a pipeline.

This ensures that the steps are executed in the correct order.

### Advantages

- Simple and organized workflow.
- Prevents inconsistent preprocessing.
- Helps prevent data leakage.
- Easy to connect with Machine Learning models.
- Makes the workflow reproducible.

In [3]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

print("Numerical Pipeline:")
print(numeric_pipeline)

print("\nCategorical Pipeline:")
print(categorical_pipeline)

Numerical Pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

Categorical Pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

## 3. What is ColumnTransformer?

`ColumnTransformer` allows different preprocessing pipelines to be applied to different columns of the dataset.

For example:

- Numerical columns → Median Imputation → Standard Scaling
- Categorical columns → Most-Frequent Imputation → One-Hot Encoding

This is useful because a dataset usually contains different types of features.

### Required Documentation

**Problem:**  
Numerical and categorical columns cannot always use the same preprocessing method.

**Analysis:**  
Numerical features require numerical transformations, while categorical features require categorical transformations.

**Technique Selected:**  
`ColumnTransformer`.

**Reason:**  
It applies the appropriate preprocessing pipeline to the correct columns.

**Implementation:**  
Numerical and categorical pipelines are passed to `ColumnTransformer`.

**Result:**  
Each feature type receives suitable preprocessing.

**Impact:**  
This produces a consistent feature matrix suitable for Machine Learning.

In [4]:
numeric_features = ["Age", "SibSp", "Parch", "Fare"]
categorical_features = ["Pclass", "Sex", "Embarked"]

preprocessor = ColumnTransformer([
    ("numerical", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

print("Preprocessor created successfully.")

Preprocessor created successfully.

## 4. Numerical Pipeline – Imputation and Scaling

Numerical features may contain missing values and may have different scales.

The numerical preprocessing workflow is:

**Numerical Features → Median Imputation → Standard Scaling**

### Median Imputation

Median is used to replace missing numerical values.

It is useful when numerical data may contain outliers because the median is less affected by extreme values than the mean.

### StandardScaler

`StandardScaler` transforms numerical values so that they are approximately centered around 0 with a standard deviation of 1.

### When to use?

This approach is useful for numerical features when missing values exist and feature scale may affect the Machine Learning algorithm.

### Required Documentation

**Problem:**  
Numerical columns may contain missing values and different value ranges.

**Analysis:**  
Missing values can prevent some algorithms from working, while different scales can affect scale-sensitive algorithms.

**Technique Selected:**  
Median imputation followed by `StandardScaler`.

**Reason:**  
Median imputation is relatively robust to outliers, while standardization puts numerical features on a comparable scale.

**Implementation:**  
`SimpleImputer(strategy="median")` followed by `StandardScaler()`.

**Result:**  
Missing numerical values are replaced and numerical features are standardized.

**Impact:**  
This can improve the performance of scale-sensitive Machine Learning algorithms.

In [5]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

print("Numerical pipeline:")
print(numeric_pipeline)

Numerical pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

## 5. Categorical Pipeline – Imputation and Encoding

Categorical features can contain missing values and text-based categories.

The categorical preprocessing workflow is:

**Categorical Features → Imputation → One-Hot Encoding**

### Most-Frequent Imputation

Missing categorical values are replaced with the most frequently occurring category.

### One-Hot Encoding

One-hot encoding converts categorical values into numerical binary columns.

For example:

Sex:

- male
- female

can become separate numerical columns.

`handle_unknown="ignore"` allows the pipeline to handle categories that were not present during training.

### Required Documentation

**Problem:**  
Categorical features may contain missing values and text categories that Machine Learning algorithms cannot directly process.

**Analysis:**  
Missing categories need to be handled, and categorical values need to be converted into numerical representation.

**Technique Selected:**  
Most-frequent imputation followed by One-Hot Encoding.

**Reason:**  
The most frequent category provides a simple categorical imputation method, while One-Hot Encoding avoids creating an artificial numerical order.

**Implementation:**  
`SimpleImputer(strategy="most_frequent")` followed by `OneHotEncoder(handle_unknown="ignore")`.

**Result:**  
Missing categorical values are replaced and categories are converted into numerical features.

**Impact:**  
The transformed categorical features can be processed by Machine Learning algorithms.

In [6]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

print("Categorical pipeline:")
print(categorical_pipeline)

Categorical pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

## 6. Combining Multiple Transformations

`ColumnTransformer` combines the numerical and categorical pipelines.

The final preprocessing workflow is:

### Numerical Features
**Age, SibSp, Parch, Fare**

→ Median Imputation

→ Standard Scaling

### Categorical Features
**Pclass, Sex, Embarked**

→ Most-Frequent Imputation

→ One-Hot Encoding

This allows different preprocessing methods to be applied to different feature types within the same dataset.

In [7]:
numeric_features = ["Age", "SibSp", "Parch", "Fare"]
categorical_features = ["Pclass", "Sex", "Embarked"]

preprocessor = ColumnTransformer([
    ("numerical", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

print("Complete preprocessing structure:")
print(preprocessor)

Complete preprocessing structure:
ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['Age', 'SibSp', 'Parch', 'Fare']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Pclass', 'Sex', 'Embarked'])])

## 7. Preparing Features and Target

The target variable is separated from the input features before preprocessing.

For this Titanic dataset:

- Target: `Survived`
- Features: Selected numerical and categorical columns

The target should not be included in the preprocessing pipeline because it is the value the model is expected to predict.

In [8]:
X = df[numeric_features + categorical_features].copy()
y = df["Survived"].copy()

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

X.head()

Feature Shape: (891, 7)
Target Shape: (891,)

    Age  SibSp  Parch     Fare  Pclass     Sex Embarked
0  22.0      1      0   7.2500       3    male        S
1  38.0      1      0  71.2833       1  female        C
2  26.0      0      0   7.9250       3  female        S
3  35.0      1      0  53.1000       1  female        S
4  35.0      0      0   8.0500       3    male        S

## 8. Train-Test Split

The dataset is divided into training and testing data before fitting the preprocessing pipeline.

This is important because preprocessing should be learned only from the training data.

### Why?

If information from the test dataset is used while fitting preprocessing steps, data leakage can occur.

The test dataset should represent unseen data.

A fixed `random_state` makes the split reproducible.

`stratify=y` maintains a similar target-class distribution in both training and testing datasets.

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (712, 7)
Testing Data: (179, 7)

## 9. Understanding fit()

`fit()` learns the required information from the training data.

For example:

- `SimpleImputer` learns the median or most frequent value.
- `StandardScaler` learns the mean and standard deviation.
- `OneHotEncoder` learns the categories.

The learned information is obtained only from the training dataset.

### Important Rule

**Fit preprocessing only on training data.**

Do not fit the preprocessing pipeline using the test dataset.

In [10]:
preprocessor.fit(X_train)

print("Preprocessor fitted using training data.")

Preprocessor fitted using training data.

## 10. Understanding transform()

`transform()` applies the preprocessing rules that were already learned during `fit()`.

The test data is transformed using the information learned from the training data.

This prevents information from the test dataset from influencing the preprocessing process.

In [11]:
X_train_transformed = preprocessor.transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

print("Transformed Training Shape:", X_train_transformed.shape)
print("Transformed Testing Shape:", X_test_transformed.shape)

Transformed Training Shape: (712, 12)
Transformed Testing Shape: (179, 12)

## 11. Understanding fit_transform()

`fit_transform()` performs two operations:

1. `fit()` – learns preprocessing information.
2. `transform()` – applies the learned preprocessing.

For training data, `fit_transform()` is commonly used.

For test data, only `transform()` should be used.

### Correct Workflow

**Training Data → fit_transform()**

**Testing Data → transform()**

### Incorrect Workflow

**Training Data → fit_transform()**

**Testing Data → fit_transform()**

The incorrect workflow can cause data leakage because the preprocessing would learn information from the test dataset.

In [12]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

print("Training data transformed using fit_transform().")
print("Testing data transformed using transform().")

print("\nTraining Shape:", X_train_transformed.shape)
print("Testing Shape:", X_test_transformed.shape)

Training data transformed using fit_transform().
Testing data transformed using transform().

Training Shape: (712, 12)
Testing Shape: (179, 12)

## 12. Complete Scikit-learn Preprocessing Pipeline

A complete preprocessing pipeline can combine the `ColumnTransformer` with a Machine Learning model.

The complete workflow becomes:

**Raw Data**

↓

**Train-Test Split**

↓

**Numerical Features → Imputation → Scaling**

↓

**Categorical Features → Imputation → Encoding**

↓

**Machine Learning Model**

This structure ensures that preprocessing is performed consistently when the model is trained and evaluated.

In [13]:
from sklearn.linear_model import LogisticRegression

model_pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

model_pipeline.fit(X_train, y_train)

accuracy = model_pipeline.score(X_test, y_test)

print("Test Accuracy:", accuracy)

Test Accuracy: 0.8044692737430168

## 13. Checking the Transformed Feature Names

After preprocessing, the original columns may become multiple numerical columns.

For example, categorical columns processed with One-Hot Encoding can produce separate columns for their categories.

Checking feature names helps us understand what the Machine Learning model receives after preprocessing.

In [14]:
feature_names = preprocessor.get_feature_names_out()

print("Number of transformed features:", len(feature_names))
print("\nTransformed Feature Names:")
print(feature_names)

Number of transformed features: 12

Transformed Feature Names:
['numerical__Age' 'numerical__SibSp' 'numerical__Parch' 'numerical__Fare'
 'categorical__Pclass_1' 'categorical__Pclass_2' 'categorical__Pclass_3'
 'categorical__Sex_female' 'categorical__Sex_male'
 'categorical__Embarked_C' 'categorical__Embarked_Q'
 'categorical__Embarked_S']

## 14. Final Preprocessing Documentation

### Problem

The dataset contains both numerical and categorical features. Some features may contain missing values, and numerical features may have different scales.

### Analysis

Numerical and categorical features require different preprocessing techniques. Applying one common technique to every column would not be appropriate.

### Technique Selected

A Scikit-learn preprocessing pipeline was selected using:

- `Pipeline`
- `ColumnTransformer`
- `SimpleImputer`
- `StandardScaler`
- `OneHotEncoder`

### Reason

A pipeline provides an organized and reproducible preprocessing workflow.

Median imputation was selected for numerical features, while most-frequent imputation was selected for categorical features.

Standardization was applied to numerical features, and One-Hot Encoding was applied to categorical features.

### Implementation

The numerical pipeline performs:

**Median Imputation → Standard Scaling**

The categorical pipeline performs:

**Most-Frequent Imputation → One-Hot Encoding**

Both pipelines are combined using `ColumnTransformer`.

### Result

Missing values are handled, numerical features are standardized, and categorical features are converted into numerical representations.

### Impact

The processed data becomes suitable for Machine Learning algorithms. Using a pipeline also helps maintain consistent preprocessing and reduces the risk of data leakage.

### Final Workflow

**Raw Dataset**

→ **Train-Test Split**

→ **Numerical: Imputation → Scaling**

→ **Categorical: Imputation → Encoding**

→ **Machine Learning Model**

→ **Prediction / Evaluation**

In [15]:
print("Preprocessing Pipeline Completed Successfully")

print("\nWorkflow:")
print("1. Train-Test Split")
print("2. Numerical Features -> Median Imputation -> Standard Scaling")
print("3. Categorical Features -> Most-Frequent Imputation -> One-Hot Encoding")
print("4. Combine using ColumnTransformer")
print("5. Train Machine Learning Model")
print("6. Evaluate on Test Data")

print("\nFinal Test Accuracy:", model_pipeline.score(X_test, y_test))

Preprocessing Pipeline Completed Successfully

Workflow:
1. Train-Test Split
2. Numerical Features -> Median Imputation -> Standard Scaling
3. Categorical Features -> Most-Frequent Imputation -> One-Hot Encoding
4. Combine using ColumnTransformer
5. Train Machine Learning Model
6. Evaluate on Test Data

Final Test Accuracy: 0.8044692737430168